services:
    acme:
        image: neilpang/acme.sh
        restart: always
        command: daemon
        network_mode: host
        pid: host
        privileged: true
        volumes:
          - acme:/acme.sh              # acme.sh state (account, configs)

          # acme.sh can also be used to deploy certificates for other
          # docker containers running on the Synology by simply mounting
          # the docker daemon socket.
          # - /var/run/docker.sock:/var/run/docker.sock

          # simple helper script to deal with the annoying issue in a similar
          # style as before by wrapping chmod and ssh in a helper script that
          # transparently replaces ssh. Synology does not support arbitrary
          # unix permissions that SSH needs when bind-mounting configs and keys
          # from a Synology volume. I highly suspect that Synology just modified
          # chmod to prevent users from changing permissions, since BTRFS
          # obviously supports them and from a privileged container chmod  works
          # perfectly... This is a rather crude but effective fix to ensure
          # that a potential permission reset will not prevent ssh from working.
          - ./fix_perms_and_ssh.sh:/usr/local/bin/ssh:ro

          - ./in_host.sh:/usr/syno/sbin/synouser:ro
          - ./in_host.sh:/usr/syno/sbin/synogroup:ro
          - ./in_host.sh:/usr/syno/sbin/synosetkeyvalue:ro
          - ./in_host.sh:/usr/syno/bin/synogetkeyvalue:ro

        environment:
          PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/syno/bin:/usr/syno/sbin
          ACCOUNT_EMAIL: here.goes@your.mail
          SYNO_USE_TEMP_ADMIN: 1
          # add commonly used environment variables here, e.g. for
          # configuring DNS challenges etc. to avoid to have them repeated
          # whenever issuing a new certificate.

volumes:
    acme:
